In [45]:
import tensorflow as tf
print(tf.__version__)

2.9.2


Creating tensors in TensorFlow

In [46]:
import tensorflow as tf
import numpy as np
np.set_printoptions(precision=3)
a = np.array([1, 2, 3], dtype=np.int32)
b = [4, 5, 6]
t_a = tf.convert_to_tensor(a)
t_b = tf.convert_to_tensor(b)

print(t_a)
print(t_b)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor([4 5 6], shape=(3,), dtype=int32)


In [47]:
# to access the values that a tensor refers to, we can simply call the .numpy() method

t_a.numpy()

array([1, 2, 3], dtype=int32)

Manipulating tensors

In [48]:
# tf.cast() to change shape to desired datatype
t_a_new = tf.cast(t_a, tf.int64)
print(t_a_new.dtype)

<dtype: 'int64'>


In [49]:
# transposing a vector
t = tf.random.uniform(shape=(3, 5))
t_T = tf.transpose(t)
print(t.shape, '-->', t_T.shape)

(3, 5) --> (5, 3)


In [50]:
# reshaping the tensor
t = tf.zeros((30, ))
t_reshape = tf.reshape(t, shape=(5, 6))
print(t_reshape.numpy())

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


Applying mathematical operations to tensors

In [51]:
tf.random.set_seed(1)

t1 = tf.random.uniform(shape=(5, 2), minval=-1.0, maxval=1.0)
t2 = tf.random.normal(shape=(5, 2), mean=0.0, stddev=1.0)

In [52]:
# hadamard product
t3 = tf.multiply(t1, t2).numpy()
t3

array([[-0.27 , -0.874],
       [-0.017, -0.175],
       [-0.296, -0.139],
       [-0.727,  0.135],
       [-0.401,  0.004]], dtype=float32)

In [53]:
# to calculate mean, sum or stddev along a particular axis
t4 = tf.math.reduce_mean(t1, axis=0).numpy()
t4

array([0.09 , 0.207], dtype=float32)

In [54]:
# matrix multiplication
t5 = tf.linalg.matmul(t1, t2, transpose_b=True).numpy()
t5

array([[-1.144,  1.115, -0.87 , -0.321,  0.856],
       [ 0.248, -0.191,  0.25 , -0.064, -0.331],
       [-0.478,  0.407, -0.436,  0.022,  0.527],
       [ 0.525, -0.234,  0.741, -0.593, -1.194],
       [-0.099,  0.26 ,  0.125, -0.462, -0.396]], dtype=float32)

Split, stack and concatenate tensors

In [55]:
tf.random.set_seed(1)
t = tf.random.uniform((6, ))
print(t.numpy())

[0.165 0.901 0.631 0.435 0.292 0.643]


In [56]:
t_splits = tf.split(t, num_or_size_splits=3)
[items.numpy() for items in t_splits]

[array([0.165, 0.901], dtype=float32),
 array([0.631, 0.435], dtype=float32),
 array([0.292, 0.643], dtype=float32)]

In [57]:
t_splits = tf.split(t, num_or_size_splits=[4, 2])
[item.numpy() for item in t_splits]

[array([0.165, 0.901, 0.631, 0.435], dtype=float32),
 array([0.292, 0.643], dtype=float32)]

In [58]:
A = tf.ones((3, ))
B = tf.zeros((2, ))
C = tf.concat([A, B], axis=0)
C.numpy()

array([1., 1., 1., 0., 0.], dtype=float32)

In [59]:
A = tf.ones((3,))
B = tf.zeros((3,))
S = tf.stack([A, B], axis=1)
S.numpy()

array([[1., 0.],
       [1., 0.],
       [1., 0.]], dtype=float32)

Building input piplines

In [60]:
a = [1.2, 3.4, 7.5, 4.1, 5.0, 1.0]
ds = tf.data.Dataset.from_tensor_slices(a)
print(ds)

<TensorSliceDataset element_spec=TensorSpec(shape=(), dtype=tf.float32, name=None)>


In [61]:
for item in ds:
  print(item)

tf.Tensor(1.2, shape=(), dtype=float32)
tf.Tensor(3.4, shape=(), dtype=float32)
tf.Tensor(7.5, shape=(), dtype=float32)
tf.Tensor(4.1, shape=(), dtype=float32)
tf.Tensor(5.0, shape=(), dtype=float32)
tf.Tensor(1.0, shape=(), dtype=float32)


In [62]:
ds_batch = ds.batch(3)
for i, elem in enumerate(ds_batch, 1):
  print('batch {}:'.format(i), elem.numpy())

batch 1: [1.2 3.4 7.5]
batch 2: [4.1 5.  1. ]


combining two tensors into a joint dataset

In [63]:
tf.random.set_seed(1)
t_x = tf.random.uniform([4, 3], dtype=tf.float32)
t_y = tf.range(4)

In [64]:
ds_x = tf.data.Dataset.from_tensor_slices(t_x)
ds_y = tf.data.Dataset.from_tensor_slices(t_y)
ds_joint = tf.data.Dataset.zip((ds_x, ds_y))
for example in ds_joint:
  print('x: ', example[0].numpy(), ' y: ', example[1].numpy())

x:  [0.165 0.901 0.631]  y:  0
x:  [0.435 0.292 0.643]  y:  1
x:  [0.976 0.435 0.66 ]  y:  2
x:  [0.605 0.637 0.614]  y:  3


In [65]:
# alternatively
ds_joint = tf.data.Dataset.from_tensor_slices((t_x, t_y))
for example in ds_joint:
  print('x: ', example[0].numpy(), ' y: ', example[1].numpy())

x:  [0.165 0.901 0.631]  y:  0
x:  [0.435 0.292 0.643]  y:  1
x:  [0.976 0.435 0.66 ]  y:  2
x:  [0.605 0.637 0.614]  y:  3


shuffle, batch, repeat

In [70]:
ds_joint

<TensorSliceDataset element_spec=(TensorSpec(shape=(3,), dtype=tf.float32, name=None), TensorSpec(shape=(), dtype=tf.int32, name=None))>

In [72]:
ds = ds_joint.shuffle(buffer_size=len(t_x))
for example in ds:
  print('x: ', example[0].numpy(), ' y: ', example[1].numpy())

x:  [0.976 0.435 0.66 ]  y:  2
x:  [0.435 0.292 0.643]  y:  1
x:  [0.165 0.901 0.631]  y:  0
x:  [0.605 0.637 0.614]  y:  3


In [73]:
ds = ds_joint.batch(batch_size=3, drop_remainder=False)
batch_x, batch_y = next(iter(ds))
print('Batch-x"\n', batch_x.numpy())
print('Batch-y"\n', batch_y.numpy())

Batch-x"
 [[0.165 0.901 0.631]
 [0.435 0.292 0.643]
 [0.976 0.435 0.66 ]]
Batch-y"
 [0 1 2]


In [75]:
ds = ds_joint.batch(3).repeat(count=2)
for i, (batch_x, batch_y) in enumerate(ds):
  print(i, batch_x.shape, batch_y.numpy())

0 (3, 3) [0 1 2]
1 (1, 3) [3]
2 (3, 3) [0 1 2]
3 (1, 3) [3]


In [76]:
ds = ds_joint.repeat(count=2).batch(3)
for i, (batch_x, batch_y) in enumerate(ds):
  print(i, batch_x.shape, batch_y.numpy())

0 (3, 3) [0 1 2]
1 (3, 3) [3 0 1]
2 (2, 3) [2 3]
